version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t 936741862101.dkr.ecr.us-east-1.amazonaws.com/a6-use1-test:latest .
      - docker tag 936741862101.dkr.ecr.us-east-1.amazonaws.com/a6-use1-test:latest 936741862101.dkr.ecr.us-east-1.amazonaws.com/a6-use1-test:$IMAGE_TAG

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 936741862101.dkr.ecr.us-east-1.amazonaws.com/a6-use1-test:$IMAGE_TAG
